# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Package to npmjs

on:
  push:
    branches: [master]
    tags:
      - ironbean@*
      - ironbean-react@*
      - ironbean-jasmine@*
      - ironbean-react-router@*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get tag name
      uses: olegtarasov/get-tag@v2.1.1
      with:
          tagRegex: "(?<package>.*)@(?<version>.*)"
    - uses: actions/checkout@v3
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      working-directory: ./packages/${{ steps.tagName.outputs.package }}
      run: npm ci
    - name: Build
      working-directory: ./packages/${{ steps.tagName.outputs.package }}
      run: npm run build
    - name: Tests
      working-directory: ./packages/${{ steps.tagName.outputs.package }}
      run: npm run test:no-watch
    - name: Publish
      working-directory: ./packages/${{ steps.tagName.outputs.package }}
      run: npm publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
